name: protect_trade
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^0.9.7

  cupertino_icons: ^0.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.3
  provider:


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/images/LOGO - Para o protótipo.png
    - videos/teste3.mp4